# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.CharField(default='abc', max_length=500),
        ),
    ]
